[default.general]
chip = "STM32F446RETx"

[default.rtt]
# The duration in ms for which the logger should retry to attach to RTT.
timeout = 3000
# Whether timestamps in the RTTUI are enabled
show_timestamps = true
# Whether to save rtt history buffer on exit.
log_enabled = true
# Where to save rtt history buffer relative to manifest path.
log_path = "./logs"
enabled = true

[release.general]
chip = "STM32F446RETx"

[release.rtt]
enabled = false